(* Boggle Module *)
  (* fun API call wrapper *)
  (* fun Create Trie *)
  (* fun Process player turn *)
  (* fun Compute all player scores *)
  (* fun Get hint (based on hint type) *)
  (* fun/module Board generation *)
(* Trie Module *)
  (* fun Insert word*)
  (* fun Lookup word*)
